metadata:
  name: myappdev-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
   - host: myapp-dev.local
     http:
      paths:
      - path: /
        backend:
           serviceName: myapp
           servicePort: 80
